FROM phusion/passenger-full:2.5.1 AS bundler

RUN bash -lc 'rvm --default use ruby-3.2.2'
ENV BUNDLER_VERSION=2.4.18
RUN gem install bundler -v 2.4.18

WORKDIR /tmp

COPY Gemfile Gemfile.lock ./
RUN bundle check || bundle install

FROM phusion/passenger-full:2.5.1 AS builder

USER root
WORKDIR /home/app/partr

RUN rm /etc/nginx/sites-enabled/default
RUN rm -f /etc/service/nginx/down
RUN rm -f /etc/service/redis/down
ADD config/nginx.conf /etc/nginx/sites-enabled/partr.conf

# Install chrome for use with puppeteer
RUN apt-get update \
    && apt-get install -y wget gnupg curl \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# Install Puppeteer
RUN corepack enable
RUN yarn add puppeteer@13.5.0
RUN npm install puppeteer

FROM builder AS assets

COPY --from=bundler /usr/local/rvm /usr/local/rvm

COPY . ./

RUN SECRET_KEY_BASE=`bin/rails secret`
RUN bin/rails assets:precompile

FROM assets AS partr

CMD ["/sbin/my_init"]
